### PR TITLE
Fix handling of arrays of ports - Fixes #1.

### LINKED ISSUE #1: fbp file generated with export feature is not recognized by soletta
fbp file generated using Export feature is not recognized by soletta, an error was returned while trying to convert the fbp file to c code. 

The fbp file contents is available from here: http://pastebin.com/N1MQwuqJ

The error returned by sol-fbp-generator is shown below:

sol-fbp-generator -j builtins.json -j test.json slv_fibonacci.fbp slv_fibonacci.cpp
./slv_fibonacci.fbp:1:29 Port 'OPERAND' from node type 'int/addition' is an array port and no index was given'
ERR: ./src/bin/sol-fbp-generator/main.c:794 generate() Couldn't generate root type function

Steps to reproduce the error: 
- The test is based in replicate the soletta example located in /soletta/src/samples/flow/basic/fibonacci.fbp
- The aspect of the slv diagram connections is founded in the attached image:

fibonacci_slv_diagram

Thank you.

### PR DESCRIPTION
**Pull request by davidmaxwaterman**
Fixes #1.
Fixes #2.

### CODE REVIEW

**Comment by bdilly** [comment]
Series seems good overall, just review usage of base_port_idx, please.

**Comment by davidmaxwaterman** [comment]
Ah, I see these changes need to happen - it makes sense...I'll make them in the morning. Thanks.

**Comment by davidmaxwaterman** [comment]
OK, I made the changes you suggested - ie removing all references to base_port_idx. The tests pass and the slv_fibonacci_v2309Complete.fbp project loads and exports with array ports on both the int/addition and switcher/int nodes.
I squashed the commits and added the signing.
Please feel free to merge.

**Comment by bdilly** [comment]
Nice, thanks @davidmaxwaterman

**Pull request merged**
